__default__:
    cpus-per-task : 2
    ntasks : 1
    mem-per-cpu : '4'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

bwa_index:
    ntasks : 1
    cpus-per-task : 4
    mem-per-cpu : '4'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

run_mapping:
    ntasks : 1
    cpus-per-task : 4
    mem-per-cpu : '2'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

samtools_stats:
    ntasks : 1
    cpus-per-task : 4
    mem-per-cpu : '3'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

samtools_merge_treatment:
    ntasks : 1
    cpus-per-task : 6
    mem-per-cpu : '3'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

samtools_merge:
    ntasks : 1
    cpus-per-task : 6
    mem-per-cpu : '3'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

diff_exp_analysis:
    ntasks: 1
    cpus-per-task: 6
    mem-per-cpu: '6'
    partition: "highmem"
    output: 'logs/stdout/{rule}/{wildcards}'
    error: 'logs/error/{rule}/{wildcards}'


run_fastp:
    ntasks : 1
    cpus-per-task : 4
    mem-per-cpu : '2'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'


