# Master sRNA_pipeline configuration file template
# ------------------------------------------

####################
# Input output data options
'DATA':
    'directories':
        'fastq_dir': "/data/projects/rymv_xantho_smallrna/pipeline_srnas/DATA2/fastq"       # samples dir with fastq
        'references_dir': "/data/projects/rymv_xantho_smallrna/pipeline_srnas/DATA2/ref"       # references dir
        'out_dir': "/data/projects/rymv_xantho_smallrna/pipeline_srnas/output10rpm"       # Out directory
        'annotation': "/data/projects/rymv_xantho_smallrna/pipeline_srnas/DATA2/annotation"
    'fasta_suffix': 'fasta'                                # file termination
    'files':
        'miRNA_gff' : '/data/projects/rymv_xantho_smallrna/pipeline_srnas/DATA2/annotation/miRBase_MSU7_MIR.gff3'
        'sample_info': "/data/projects/rymv_xantho_smallrna/pipeline_srnas/DATA2/sample_info.txt"
        'de_comparisons_file': "/data3/projects/pixies/scripts/treatmentsComparisons_2012.csv"
        'filter_gff': "/data3/projects/pixies/reference_genomic_data/NB_genome/Oryza_sativa_genomic_refseq_IRGSP_seqlevels.gff3"
#NASID: "NAS2"

################################
# Params for tools:
PARAMS:
    FASTP:
        options: "" # Carefull ! Quality trimming and adaptater removal is enabled by default.
    SHORTSTACK:
        dicermin: 20
        dicermax: 24
        mincov: 10rpm
        pad: 75
        foldsize: 300
        strand_cutoff: 0.8
    DE_ANALYSIS:
        # feature filtering based on total read counts
        minRowSumTreshold: 30
        # DESeq2 modeling with GLM
        variableOfInterest: "Treatment"
        batch: "Experiment"
        locfunc: "shorth" # "median"
        fitType: "parametric"
        sizeFactEstimMethod: "iterate" # "ratio" # "poscounts"
        pAdjustMethod: "BH"
        cooksCutoff: "TRUE"
        independentFiltering: "FALSE"
        lfcThreshold: 2
        altHypothesis: "greaterAbs"
        alpha: 0.05
        # DESeq2 VSR transformation method
        typeTrans: "rlog"

##############################
# Location of various software

SINGULARITY:
    "MAIN": "Containers/Singularity.R.simg"
