# Master sRNA_pipeline configuration file template
# ------------------------------------------

####################
# Input output data options
'DATA':
    'directories':
        'fastq_dir': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/fastq"       # samples dir with fastq
        'out_dir': "/data/projects/rymv_xantho_smallrna/srnamake/output2rpm"       # Out directory
    'fasta_suffix': 'fa'                                # file termination
    'files':
        'reference': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/ref/RiceRYMV2.fasta"
        'annotation': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/annotation/RiceRYMV2.gtf"
        'miRNA_gff' : '/data/projects/rymv_xantho_smallrna/srnamake/DATA2/annotation/miRBase_MSU7_MIR.gff3'
        'sample_info': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/sample_info.txt"
        'de_comparisons_file': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/treatmentsComparisons.csv"
        'filter_gff': "/data/projects/rymv_xantho_smallrna/srnamake/DATA2/Oryza_sativa_genomic_refseq_IRGSP_seqlevels.gff3"
#NASID: "NAS2"

################################
# Params for tools:
PARAMS:
    FASTP:
	    options: "--overrepresentation_analysis --length_required 18 --length_limit 30"
        #options: "-A -Q -L -G --overrepresentation_analysis"
    BWA_ALN:
        options: ""
    SHORTSTACK:
        dicermin: 20
        dicermax: 24
        mincov: 1rpm
        pad: 75
        foldsize: 300
        strand_cutoff: 0.8
    DE_ANALYSIS:
        # feature filtering based on total read counts
        minRowSumTreshold: 30
        # DESeq2 modeling with GLM
        variableOfInterest: "Treatment"
        batch: "Experiment"
        locfunc: "shorth" # "median"
        fitType: "parametric"
        sizeFactEstimMethod: "iterate" # "ratio" # "poscounts"
        pAdjustMethod: "BH"
        cooksCutoff: "TRUE"
        independentFiltering: "FALSE"
        lfcThreshold: 1
        altHypothesis: "greaterAbs"
        alpha: 0.05
        # DESeq2 VSR transformation method
        typeTrans: "rlog"

##############################
# Location of various software

SINGULARITY:
    "MAIN": "Containers/Singularity.R.simg"
