# Master sRNA_pipeline configuration file template
# ------------------------------------------

####################
# Input output data options
'DATA':
    'directories':
        # ARE THE '/' COMPULSORY IN FOLDER PATHS?
        'fastq_dir': "/data/projects/rymv_xantho_smallrna/seb/bai3_dataset_input/fastq"       # samples dir with fastq
        'references_dir': "/data/projects/rymv_xantho_smallrna/seb/bai3_dataset_input/ref"       # references dir
        'out_dir': "/data/projects/rymv_xantho_smallrna/seb/bai3_dataset_output/"       # Out directory
        'annotation': "/data/projects/rymv_xantho_smallrna/seb/bai3_dataset_input/annot"
    'fasta_suffix': 'fa'                                # file termination -> WHAT IF files have different extentions (eg fa, fast, ...)?
    'files':
        'miRNA_gff' : '/data3/projects/pixies/reference_genomic_data/NB_genome/miRBase_MSU7_MIR.gff3'
        'sample_info': "/data/projects/rymv_xantho_smallrna/seb/bai3_dataset_input/samplesInfo_BAI3_trimmed.txt"
#NASID: "NAS2"

################################
# Params for tools:
PARAMS:
    SHORTSTACK:
        dicermin: 20
        dicermax: 24
        mincov: 10rpm
        pad: 75
        foldsize: 300
        strand_cutoff: 0.8

##############################
# Location of various software
#
# the variable must load soft on the $PATH environement
#MODULES:
#    "SAMTOOLS": "module load bioinfo/samtools/1.10"         # use for filter reads and convert sam to bam
#    "PYTHON3": "module load system/python/3.7.2"           # Python3 >=3.6 with require libraries
#    "BWA": "module load bioinfo/bwa/0.7.17"                # for make the mapping
#    "SHORTSTACK": "module load bioinfo/ShortStack/3.8.4"
#    "PERL" : "module load system/perl/5.16.3"

#MODULES:
#    "SAMTOOLS": " "         # use for filter reads and convert sam to bam
#    "PYTHON3": " "           # Python3 >=3.6 with require libraries
#    "BWA": " "                # for make the mapping
#    "SHORTSTACK": "export PATH='/home/comte/Documents/DIVERS/TOOLS/ShortStack/:$PATH'"
#    "PERL" : ""

SINGULARITY:
    "MAIN" : "/data/projects/rymv_xantho_smallrna/pipeline_srnas/Containers/Singularity.R.simg"


